- name: conditions
  hosts: localhost
  connection: local
  tasks:
    - name: print veg name
      ansible.builtin.debug:
        msg: veg name  - carrot
      when: veg == "yes"

    - name: print fruit name
      ansible.builtin.debug:
        msg: veg name  - banana
      when: fruit == "yes"

    - name: print veg name1
      ansible.builtin.debug:
        msg: veg name  - carrot
      when: veg | bool