- name: conditions
  hosts: localhost
  connection: local
  tasks:
    - name: print veg name
      ansible.builtin.debug:
        msg: veg name  - carrot

    - name: print fruit name
      ansible.builtin.debug:
        msg: veg name  - banana