- name: conditions
  hosts: localhost
  connection: local
  tasks:
    - name: Restart a container
      community.docker.docker_container:
        name: sample
        image: docker.io/nginx
        state: started
        ports:
          - "8080:80"
