- name: Retrieve secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Get Secrets
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=demo/data/ssh:username token={{ token }}', url=http://vault.prashumps.online:8200') }}"