- name: Retrieve secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Get Secrets
#      ansible.builtin.debug:
#        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=demo/data/ssh:user token={{ token }} url=http://vault.prashumps.online:8200') }}"

    - name: Get password
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-dev/frontend:cart_url token={{ token }} url=http://vault-int.prashumps.online:8200') }}"

