# loops
- name: loops example
  hosts: localhost
  connection: local
  tasks:
    - name: print veg name
      ansible.builtin.debug:
        msg: veg name are -
      loop:
        - carrot
        - drumstick
        - bitter guard