# loops
- name: loops example
  hosts: localhost
  connection: local
  tasks:
    - name: print veg name
      ansible.builtin.debug:
        msg: veg name are - {{ item }}
      loop:
        - carrot
        - drumstick
        - bitter guard

    - name: print veg names
      ansible.builtin.debug:
        msg: veg name are - {{ iter["name"] }} , Qty - {{ iter.qty }}
      loop:
        - { name: carrot, qty: 10}
        - { name: tomato, qty: 20}
