- name: test playbook
  hosts: all
  tasks:
    - name: demo task
      ansible.builtin.debug:
        msg: Hello I am in ansible world


# variables
- name: play level variables
  hosts: localhost
  connection: local
  vars:
    url: play.example.com  # all tasks can access this variable
  tasks:
    - name : print url
      ansible.builtin.debug:
        msg: url is  - {{ url }}


- name: Task level variables
  hosts: localhost
  connection: local
  tasks:
    - name : print url
      ansible.builtin.debug:
        msg: url is  - {{ url }}
      vars:
        url: tasks.example.com  # task level variable