- name: test playbook
  hosts: all
  tasks:
    - name: demo task
      ansible.builtin.debug:
        msg: Hello I am in ansible world


# variables
- name: play level variables
  hosts: localhost
  connection: local
  vars:
    url: play.example.com  # all tasks can access this variable
  tasks:
    - name : print url
      ansible.builtin.debug:
        msg: url is  - {{ url }}


- name: Task level variables
  hosts: localhost
  connection: local
  tasks:
    - name : print url
      ansible.builtin.debug:
        msg: url is  - {{ url }}
      vars:
        url: tasks.example.com  # task level variable


#  commandline level
#  Task level
#  Play level
#  inventory level
#  Error if no variable declared

#variable data types
#string, Number, Boolean

- name : Variable types
  hosts: localhost
  connection: local
  vars:
    x: abc
    y: 100
    z: true
  tasks:
    - name : print values
      ansible.builtin.debug:
        msg: x - {{ x }} , y - {{ y }} , z - {{ z }}

# variable declaration types
# Normal, List, Map

- name : Variable types
  hosts: localhost
  connection: local
  vars:
    x: abc
    y:
      - 100
      - 200
    z:
      url: sample
      domain: example.com
  tasks:
    - name : print values
      ansible.builtin.debug:
        msg: x - {{ x }} , y - {{ y[0] }} , z - {{ z["url"] }}